# Generated by Django 3.2.15 on 2022-08-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
