# Generated by Django 3.2.15 on 2022-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
