# Generated by Django 3.2.15 on 2022-08-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220830_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Spices', 'Spices'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
