# Generated by Django 3.2.15 on 2022-08-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
